In [2]:
import pandas as pd 

customers = pd.read_csv(r"C:\Users\Abdul\Documents\VS_code_projects\OLIST-Customer-Purchase-Analytics\data\cleaned\olist_customers_dataset.csv")
orders = pd.read_csv(r"C:\Users\Abdul\Documents\VS_code_projects\OLIST-Customer-Purchase-Analytics\data\cleaned\olist_orders_dataset.csv")
order_items = pd.read_csv(r"C:\Users\Abdul\Documents\VS_code_projects\OLIST-Customer-Purchase-Analytics\data\cleaned\olist_order_items_dataset.csv") 

print("customers: ", customers.shape)
print("orders: ", orders.shape)
print("order items: ", order_items.shape)

customers:  (99441, 5)
orders:  (99441, 8)
order items:  (112650, 7)

In [3]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [4]:
orders.head(
)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [5]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [6]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [7]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [8]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [9]:
print("Customers columns:")
print(customers.columns.tolist())

print("\nOrders columns:")
print(orders.columns.tolist())

print("\nOrder items columns:")
print(order_items.columns.tolist())

Customers columns:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Orders columns:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

Order items columns:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

In [13]:
orders["order_status"].value_counts(dropna = False)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [15]:
orders["order_status"].value_counts(normalize = True, dropna = False)

order_status
delivered      0.970203
shipped        0.011132
canceled       0.006285
unavailable    0.006124
invoiced       0.003158
processing     0.003027
created        0.000050
approved       0.000020
Name: proportion, dtype: float64

In [16]:
orders["order_purchase_timestamp"].min()

'2016-09-04 21:15:19'

In [17]:
orders["order_purchase_timestamp"].max()

'2018-10-17 17:30:18'

In [18]:
orders["order_purchase_timestamp"] = pd.to_datetime(orders['order_purchase_timestamp'])

In [22]:
orders["order_purchase_timestamp"].min()

Timestamp('2016-09-04 21:15:19')

In [20]:
orders["order_purchase_timestamp"].max()

Timestamp('2018-10-17 17:30:18')

In [24]:
print("Unique Customer id: ", customers["customer_id"].nunique())
print("Unique customer_unique id", customers["customer_unique_id"].nunique())

Unique Customer id:  99441
Unique customer_unique id 96096

In [26]:
customer_id_mapping = customers.groupby("customer_id")["customer_unique_id"].nunique()

customer_id_mapping.value_counts()

customer_unique_id
1    99441
Name: count, dtype: int64

In [27]:
unique_id_mapping = customers.groupby("customer_unique_id")["customer_id"].nunique()

unique_id_mapping.value_counts()

customer_id
1     93099
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

In [ ]:
orders_per_customer = (orders.merge(customers[["customer_id", "customer_unique_id"]],on="customer_id",how="left") #Selecting only the customerid and unique id for the join
                       .groupby("customer_unique_id")["order_id"].nunique())

In [ ]:
orders_per_customer.describe() #we see mostly 1, and a maximum up 17 orders per customer

count    96096.000000
mean         1.034809
std          0.214384
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         17.000000
Name: order_id, dtype: float64

In [31]:
orders_per_customer.value_counts().sort_index()

order_id
1     93099
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

In [32]:
customers.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [33]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [34]:
order_items.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [35]:
print("rows in order items:", len(order_items))
print("unique orders in order items:", order_items["order_id"].nunique())
print("unique order ids in orders:", orders["order_id"].nunique())

rows in order items: 112650
unique orders in order items: 98666
unique order ids in orders: 99441

In [36]:
order_items[["order_id", "order_item_id", "price", "freight_value"]].head()

                           order_id  order_item_id   price  freight_value
0  00010242fe8c5a6d1ba2dd792cb16214              1   58.90          13.29
1  00018f77f2f0320c557190d7a144bdd3              1  239.90          19.93
2  000229ec398224ef6ca0657da4fc703e              1  199.00          17.87
3  00024acbcdf0a6daa1e931b038114c75              1   12.99          12.79
4  00042b26cf59d7ce69dfabb4e55b4fd9              1  199.90          18.14

In [39]:
items_per_order = (order_items.groupby("order_id")["order_item_id"].nunique())

items_per_order.describe()

count    98666.000000
mean         1.141731
std          0.538452
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         21.000000
Name: order_item_id, dtype: float64

In [43]:
items_per_order.value_counts().sort_index()

order_item_id
1     88863
2      7516
3      1322
4       505
5       204
6       198
7        22
8         8
9         3
10        8
11        4
12        5
13        1
14        2
15        2
20        2
21        1
Name: count, dtype: int64

### Short analysis section
|Questions|
|:--|
|What does the dataset allow us to model?|
|Can we correctly identify customer behaviour?|
|Can we seperate past behaviour from current behaviour?|
|Can we build a prediction problem?|

In [65]:
customer_mapping = customers.groupby("customer_unique_id")["customer_id"].nunique()
customer_mapping.describe()

count    96096.000000
mean         1.034809
std          0.214384
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         17.000000
Name: customer_id, dtype: float64

In [66]:
customer_mapping.value_counts().sort_index()

customer_id
1     93099
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

In [67]:
print("Customer unique id values linked to multiple customer ids: ", (customer_mapping > 1).sum())

Customer unique id values linked to multiple customer ids:  2997

In [ ]:
#checking reverse relationship aswell

customer_reverse_map = customers.groupby("customer_id")["customer_unique_id"].nunique()

customer_reverse_map.describe()
#standard deviation 0, min and max 1 value. value appears to be unique for each.

count    99441.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
Name: customer_unique_id, dtype: float64

In [70]:
customer_reverse_map.value_counts().sort_index()

customer_unique_id
1    99441
Name: count, dtype: int64

In [72]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [73]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [75]:
customer_orders = orders.merge(customers[["customer_id", 'customer_unique_id']], on = "customer_id", how = "left") 
customer_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6

In [78]:
print("orders: ", len(orders))
print("customer orders merged: ", len(customer_orders))

print("orders without customer unique id: ", customer_orders["customer_unique_id"].isna().sum())

orders:  99441
customer orders merged:  99441
orders without customer unique id:  0

In [84]:
customer_order_counts = customer_orders.groupby("customer_unique_id")["order_id"].nunique()
customer_order_counts.value_counts().sort_index()

order_id
1     93099
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

In [98]:
customer_purchase_dates = (customer_orders.groupby("customer_unique_id")["order_purchase_timestamp"].agg(["min", "max", "count"]).reset_index())
customer_purchase_dates = customer_purchase_dates.rename(columns = {

    "min" : "First Purchase Date",
    "max" : "Last Purchase Date",
    "count": "Order Count"
    })
customer_purchase_dates.describe()

              First Purchase Date          Last Purchase Date   Order Count
count                       96096                       96096  96096.000000
mean   2017-12-30 19:19:10.429206  2018-01-02 12:40:19.655865      1.034809
min           2016-09-04 21:15:19         2016-09-04 21:15:19      1.000000
25%           2017-09-11 19:52:06  2017-09-15 09:04:17.250000      1.000000
50%           2018-01-18 13:33:08         2018-01-21 19:39:16      1.000000
75%           2018-05-04 10:38:45  2018-05-06 20:14:49.750000      1.000000
max           2018-10-17 17:30:18         2018-10-17 17:30:18     17.000000
std                           NaN                         NaN      0.214384